# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
minecraft_version_range=[26.1.2]
mod_name=Dedicated MC UPnP
mod_version = 3.1.1
mod_group_id = pigcart.dedicatedmcupnp
mod_id = dedicatedmcupnp
mod_license=MIT

# Minecraft properties
minecraft_version = 26.1.2


# Dependencies
neo_version=26.1.2.76
